name: Makefile CI

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=3m

    - name: Run test
      run: make test
      
    - name: Run build
      run: make build-all
      if: github.event_name != 'pull_request'

    - name: Upload assets
      uses: AButler/upload-release-assets@v2.0
      if: github.event_name != 'pull_request'
      with:
        files: 'out/bin/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
