name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m

      - name: Run test
        run: make test

      - name: Run build
        run: make build-all

      - name: Upload assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'out/bin/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
